/** Maps common city names/aliases to Craigslist subdomains */
export const CITY_TO_CL: Record<string, string> = {
  "new york": "newyork",
  "new york city": "newyork",
  nyc: "newyork",
  "los angeles": "losangeles",
  la: "losangeles",
  "san francisco": "sfbay",
  sf: "sfbay",
  "bay area": "sfbay",
  chicago: "chicago",
  seattle: "seattle",
  denver: "denver",
  dallas: "dallas",
  houston: "houston",
  phoenix: "phoenix",
  portland: "portland",
  austin: "austin",
  miami: "miami",
  atlanta: "atlanta",
  boston: "boston",
  minneapolis: "minneapolis",
  "san diego": "sandiego",
  "las vegas": "lasvegas",
  detroit: "detroit",
  philadelphia: "philadelphia",
  charlotte: "charlotte",
  nashville: "nashville",
  "salt lake city": "saltlakecity",
  slc: "saltlakecity",
  sacramento: "sacramento",
  "san jose": "sfbay",
  raleigh: "raleigh",
  tampa: "tampa",
  orlando: "orlando",
  pittsburgh: "pittsburgh",
  "kansas city": "kansascity",
  baltimore: "baltimore",
  indianapolis: "indianapolis",
  columbus: "columbus",
  memphis: "memphis",
  jacksonville: "jacksonville",
  "san antonio": "sanantonio",
  cincinnati: "cincinnati",
  richmond: "richmond",
  "new orleans": "neworleans",
  "st louis": "stlouis",
  "saint louis": "stlouis",
  buffalo: "buffalo",
  hartford: "hartford",
  norfolk: "norfolk",
  "virginia beach": "norfolk",
  washington: "washingtondc",
  dc: "washingtondc",
  "washington dc": "washingtondc",
};

/** Maps common city names/aliases to Facebook Marketplace city slugs */
export const CITY_TO_FB: Record<string, string> = {
  "new york": "nyc",
  nyc: "nyc",
  "los angeles": "la",
  la: "la",
  "san francisco": "sanfrancisco",
  sf: "sanfrancisco",
  "bay area": "sanfrancisco",
  chicago: "chicago",
  seattle: "seattle",
  denver: "denver",
  dallas: "dallas",
  houston: "houston",
  phoenix: "phoenix",
  portland: "portland",
  austin: "austin",
  miami: "miami",
  atlanta: "atlanta",
  boston: "boston",
  minneapolis: "minneapolis",
  "san diego": "sandiego",
  "las vegas": "lasvegas",
  detroit: "detroit",
  philadelphia: "philadelphia",
  nashville: "nashville",
  sacramento: "sacramento",
  raleigh: "raleigh",
  tampa: "tampa",
  orlando: "orlando",
  pittsburgh: "pittsburgh",
  "kansas city": "kansascity",
  "salt lake city": "saltlakecity",
  slc: "saltlakecity",
  baltimore: "baltimore",
  charlotte: "charlotte",
  indianapolis: "indianapolis",
  columbus: "columbus",
  memphis: "memphis",
  jacksonville: "jacksonville",
  "san antonio": "sanantonio",
  "san jose": "sanjose",
  cincinnati: "cincinnati",
  richmond: "richmond",
  "new orleans": "neworleans",
  "st louis": "stlouis",
  "saint louis": "stlouis",
  buffalo: "buffalo",
  hartford: "hartford",
  norfolk: "norfolk",
  "virginia beach": "virginiabeach",
  washington: "washington",
  dc: "washington",
  "washington dc": "washington",
};
