/** Maps common city names/aliases to Craigslist subdomains */
export const CITY_TO_CL: Record<string, string> = {
  "new york": "newyork",
  "new york city": "newyork",
  nyc: "newyork",
  "los angeles": "losangeles",
  la: "losangeles",
  "san francisco": "sfbay",
  sf: "sfbay",
  "bay area": "sfbay",
  chicago: "chicago",
  seattle: "seattle",
  denver: "denver",
  dallas: "dallas",
  houston: "houston",
  phoenix: "phoenix",
  portland: "portland",
  austin: "austin",
  miami: "miami",
  atlanta: "atlanta",
  boston: "boston",
  minneapolis: "minneapolis",
  "san diego": "sandiego",
  "las vegas": "lasvegas",
  detroit: "detroit",
  philadelphia: "philadelphia",
  charlotte: "charlotte",
  nashville: "nashville",
  "salt lake city": "saltlakecity",
  slc: "saltlakecity",
  sacramento: "sacramento",
  "san jose": "sfbay",
  raleigh: "raleigh",
  tampa: "tampa",
  orlando: "orlando",
  pittsburgh: "pittsburgh",
  "kansas city": "kansascity",
  baltimore: "baltimore",
  indianapolis: "indianapolis",
  columbus: "columbus",
  memphis: "memphis",
  jacksonville: "jacksonville",
  "san antonio": "sanantonio",
  cincinnati: "cincinnati",
  richmond: "richmond",
  "new orleans": "neworleans",
  "st louis": "stlouis",
  "saint louis": "stlouis",
  buffalo: "buffalo",
  hartford: "hartford",
  norfolk: "norfolk",
  "virginia beach": "norfolk",
  washington: "washingtondc",
  dc: "washingtondc",
  "washington dc": "washingtondc",
};

/** Maps common city names/aliases to Facebook Marketplace city slugs */
export const CITY_TO_FB: Record<string, string> = {
  "new york": "nyc",
  nyc: "nyc",
  "los angeles": "la",
  la: "la",
  "san francisco": "sanfrancisco",
  sf: "sanfrancisco",
  "bay area": "sanfrancisco",
  chicago: "chicago",
  seattle: "seattle",
  denver: "denver",
  dallas: "dallas",
  houston: "houston",
  phoenix: "phoenix",
  portland: "portland",
  austin: "austin",
  miami: "miami",
  atlanta: "atlanta",
  boston: "boston",
  minneapolis: "minneapolis",
  "san diego": "sandiego",
  "las vegas": "lasvegas",
  detroit: "detroit",
  philadelphia: "philadelphia",
  nashville: "nashville",
  sacramento: "sacramento",
  raleigh: "raleigh",
  tampa: "tampa",
  orlando: "orlando",
  pittsburgh: "pittsburgh",
  "kansas city": "kansascity",
  "salt lake city": "saltlakecity",
  slc: "saltlakecity",
  baltimore: "baltimore",
  charlotte: "charlotte",
  indianapolis: "indianapolis",
  columbus: "columbus",
  memphis: "memphis",
  jacksonville: "jacksonville",
  "san antonio": "sanantonio",
  "san jose": "sanjose",
  cincinnati: "cincinnati",
  richmond: "richmond",
  "new orleans": "neworleans",
  "st louis": "stlouis",
  "saint louis": "stlouis",
  buffalo: "buffalo",
  hartford: "hartford",
  norfolk: "norfolk",
  "virginia beach": "virginiabeach",
  washington: "washington",
  dc: "washington",
  "washington dc": "washington",
};

/**
 * Representative cities spread across the US for nationwide Facebook search.
 * Each entry is [displayName, fbSlug]. Covers major metro regions.
 */
export const NATIONWIDE_FB_CITIES: [string, string][] = [
  ["New York", "nyc"],
  ["Los Angeles", "la"],
  ["Chicago", "chicago"],
  ["Houston", "houston"],
  ["Phoenix", "phoenix"],
  ["Seattle", "seattle"],
  ["Denver", "denver"],
  ["Atlanta", "atlanta"],
  ["Miami", "miami"],
  ["Dallas", "dallas"],
  ["Boston", "boston"],
  ["Minneapolis", "minneapolis"],
  ["Philadelphia", "philadelphia"],
  ["Nashville", "nashville"],
  ["Portland", "portland"],
];

/** Deduplicated, sorted city options for the browse page dropdown */
export const FB_CITY_OPTIONS: { label: string; slug: string }[] = (() => {
  const seen = new Set<string>();
  const options: { label: string; slug: string }[] = [];
  for (const [name, slug] of Object.entries(CITY_TO_FB)) {
    if (seen.has(slug)) continue;
    seen.add(slug);
    // Capitalize each word for the label
    const label = name.replace(/\b\w/g, (c) => c.toUpperCase());
    options.push({ label, slug });
  }
  return options.sort((a, b) => a.label.localeCompare(b.label));
})();
